'use client'

import { useMemo, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, BarChart3, ChevronDown, CircleHelp, Database, FileCheck2, Filter, Menu, Moon, RefreshCw, Search, ShieldCheck, Sun, X } from 'lucide-react'

type View = 'Dashboard' | 'Analysis' | 'Disparity' | 'Data Quality' | 'Statistics' | 'DGCA Benchmark' | 'Public API'

const nav: View[] = ['Dashboard', 'Analysis', 'Disparity', 'Data Quality', 'Statistics', 'DGCA Benchmark', 'Public API']
const routes = ['All routes', 'BLR-CCU', 'DEL-BOM', 'BOM-HYD', 'DEL-BLR']
const airlines = ['All airlines', '6E · IndiGo', 'AI · Air India', 'UK · Vistara', 'IX · Air India Express']
const windows = ['All booking windows', '0-3 days', '4-7 days', '8-15 days', '16-30 days', '31-60 days', '61-90 days']
const observations = [
  ['BLR-CCU', '6E · IndiGo', '0-3 days', '2026-09-20', '0', '₹5,853.92'],
  ['BLR-CCU', 'AI · Air India', '4-7 days', '2026-09-24', '4', '₹5,598.75'],
  ['DEL-BOM', 'UK · Vistara', '8-15 days', '2026-09-28', '8', '₹6,212.20'],
  ['BOM-HYD', '6E · IndiGo', '16-30 days', '2026-10-06', '16', '₹3,645.15'],
  ['DEL-BLR', 'AI · Air India', '31-60 days', '2026-10-21', '31', '₹4,884.61'],
]

function formatNumber(value: number) { return new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2 }).format(value) }

export function AirfarePlatform() {
  const [view, setView] = useState<View>('Dashboard')
  const [dark, setDark] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [route, setRoute] = useState('All routes')
  const [airline, setAirline] = useState('All airlines')
  const [bookingWindow, setBookingWindow] = useState('All booking windows')
  const [traceDate, setTraceDate] = useState('2026-09-20')

  const pageDescription = useMemo(() => ({
    Dashboard: 'A transparent view of India\'s synthetic national airfare movement.',
    Analysis: 'Compare fare profiles across routes, airlines and booking windows.',
    Disparity: 'Understand how airfare dispersion varies across the network.',
    'Data Quality': 'Review validation controls and the synthetic anomaly feed.',
    Statistics: 'Dataset metadata and the index construction methodology.',
    'DGCA Benchmark': 'Reconstruct published index values from stored contributions.',
    'Public API': 'Explore the read-only endpoints powering this prototype.',
  } as Record<View, string>)[view], [view])

  function navigate(next: View) { setView(next); setMenuOpen(false); globalThis.window?.scrollTo({ top: 0, behavior: 'smooth' }) }

  return <div className={dark ? 'app dark' : 'app'}>
    <header className="site-header">
      <div className="shell header-inner">
        <button className="brand" onClick={() => navigate('Dashboard')} aria-label="Go to dashboard"><span className="brand-mark">AI</span><span><strong>AirFare</strong><small>Intelligence Platform</small></span></button>
        <nav className={`nav ${menuOpen ? 'open' : ''}`} aria-label="Primary navigation">{nav.map(item => <button key={item} className={view === item ? 'active' : ''} onClick={() => navigate(item)}>{item}{item === 'Public API' && <span className="nav-arrow">↗</span>}</button>)}</nav>
        <div className="header-actions"><button className="icon-button theme-toggle" onClick={() => setDark(!dark)} aria-label={dark ? 'Use light theme' : 'Use dark theme'}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="icon-button menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></div>
      </div>
    </header>
    <div className="synthetic-banner"><div className="shell"><ShieldCheck size={15} /><span><strong>Synthetic prototype</strong> · All figures are simulated for SIH26056 and are not official statistics.</span><button aria-label="Learn more"><CircleHelp size={14} /></button></div></div>
    <main className="shell main-content">
      <div className="page-heading"><div><p className="eyebrow">SIH26056 / AIRFARE PRICE INDEX</p><h1>{view}</h1><p className="lede">{pageDescription}</p></div><div className="date-control"><label htmlFor="trace-date">Trace date</label><input id="trace-date" type="date" value={traceDate} onChange={e => setTraceDate(e.target.value)} /></div></div>
      {view === 'Dashboard' && <Dashboard navigate={navigate} />}
      {view === 'Analysis' && <Analysis route={route} airline={airline} window={bookingWindow} setRoute={setRoute} setAirline={setAirline} setWindow={setBookingWindow} />}
      {view === 'Disparity' && <Disparity route={route} airline={airline} window={bookingWindow} setRoute={setRoute} setAirline={setAirline} setWindow={setBookingWindow} />}
      {view === 'Data Quality' && <DataQuality />}
      {view === 'Statistics' && <Statistics />}
      {view === 'DGCA Benchmark' && <Benchmark />}
      {view === 'Public API' && <ApiDocs />}
    </main>
    <footer className="site-footer"><div className="shell footer-inner"><div><strong>AirFare Intelligence Platform</strong><p>Research prototype for transparent airfare measurement.</p></div><div className="footer-note"><span className="status-dot" />Synthetic data only · Updated 20 Sep 2026 <span className="hatchable">Built on Hatchable</span></div></div></footer>
  </div>
}

function Dashboard({ navigate }: { navigate: (v: View) => void }) { return <>
  <section className="kpi-grid"><Kpi label="Selected index" value="128.18" meta="2026-09-20" delta="+2.41%" positive /><Kpi label="Fare observations" value="660" meta="valid observations" delta="+28 today" positive /><Kpi label="Routes represented" value="22" meta="active routes" delta="100% coverage" positive /></section>
  <section className="panel hero-chart"><div className="panel-header"><div><p className="eyebrow">INDEX SERIES · BASE 2026-01-30 = 100</p><h2>National Airfare Index</h2></div><span className="legend"><i className="legend-line" />Published index</span></div><div className="chart-wrap" aria-label="Line chart showing the synthetic national airfare index rising from 100 to 128.18"><Chart /></div><div className="chart-foot"><span>Jan 30, 2026</span><span>Apr 2026</span><span>Jul 2026</span><span>Sep 20, 2026</span></div></section>
  <div className="two-col"><section className="panel"><div className="panel-header"><div><p className="eyebrow">SELECTED TRACE DATE</p><h2>Day-level signal</h2></div><span className="badge badge-teal">20 Sep 2026</span></div><div className="signal-grid"><div><span>Exact index</span><strong>128.1833</strong></div><div><span>Observations</span><strong>660</strong></div><div><span>Routes</span><strong>22</strong></div></div><div className="change-callout"><ArrowUpRight size={16} /><span><strong>+3.01 pts</strong> vs previous day</span></div></section><section className="panel"><div className="panel-header"><div><p className="eyebrow">TRACEABILITY</p><h2>Why did the index change?</h2></div><button className="text-button" onClick={() => navigate('Analysis')}>Explore analysis ↗</button></div><div className="trace-chain">{['National index', 'Route', 'Airline', 'Booking window', 'Fare observation'].map((step, i) => <div className="trace-step" key={step}><span>{String(i + 1).padStart(2, '0')}</span><strong>{step}</strong>{i < 4 && <b>→</b>}</div>)}</div><div className="trace-stats"><div><span>Trace sum vs gap</span><strong>99.8% <em>aligned</em></strong></div><div><span>Top route</span><strong>DEL–BOM</strong></div></div></section></div>
  <section className="panel"><div className="panel-header"><div><p className="eyebrow">OBSERVATION LEDGER</p><h2>Fare observations for selected day</h2><p className="panel-subtitle">Showing 5 of 660 valid records · values in INR</p></div><button className="icon-button" aria-label="Refresh observations"><RefreshCw size={16} /></button></div><ObservationTable /></section>
  <div className="three-col"><Contribution title="Route contribution" rows={[['DEL–BOM','+1.18 pts'],['BLR–CCU','+0.87 pts'],['BOM–HYD','+0.45 pts']]} /><Contribution title="Airline contribution" rows={[['6E · IndiGo','+1.34 pts'],['AI · Air India','+0.92 pts'],['UK · Vistara','+0.51 pts']]} /><Contribution title="Booking window" rows={[['0–3 days','+1.61 pts'],['4–7 days','+0.88 pts'],['8–15 days','+0.42 pts']]} /></div>
</> }
function Kpi({ label, value, meta, delta, positive }: { label: string; value: string; meta: string; delta: string; positive?: boolean }) { return <article className="kpi-card"><div className="kpi-top"><span>{label}</span><span className={positive ? 'delta positive' : 'delta'}>{positive ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{delta}</span></div><strong>{value}</strong><small>{meta}</small></article> }
function Chart() { const points = '0,155 22,150 44,151 66,140 88,143 110,132 132,136 154,124 176,130 198,113 220,117 242,104 264,111 286,97 308,101 330,88 352,93 374,79 396,84 418,70 440,74 462,64 484,69 506,51 528,57 550,44 572,48 594,35 616,42 638,29'; return <svg className="line-chart" viewBox="0 0 660 190" role="img" aria-label="Synthetic index line chart"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#169c9c" stopOpacity=".28" /><stop offset="1" stopColor="#169c9c" stopOpacity="0" /></linearGradient></defs>{[30,70,110,150].map(y => <line key={y} x1="0" x2="660" y1={y} y2={y} className="gridline" />)}<polyline points={`0,180 ${points} 660,180`} fill="url(#area)" stroke="none" /><polyline points={points} fill="none" stroke="#1ca3a3" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /><circle cx="638" cy="29" r="5" fill="#f1b55b" stroke="var(--surface)" strokeWidth="3" /></svg> }
function ObservationTable() { return <div className="table-scroll"><table><thead><tr>{['Route','Airline','Booking window','Departure','Days before','Fare'].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{observations.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j} className={j === 5 ? 'numeric strong' : j === 4 ? 'numeric' : ''}>{j === 1 ? <span className="airline-pill">{cell}</span> : cell}</td>)}</tr>)}</tbody></table></div> }
function Contribution({ title, rows }: { title: string; rows: string[][] }) { return <section className="panel contribution"><div className="panel-header"><h3>{title}</h3><BarChart3 size={16} /></div>{rows.map(([name, value]) => <div className="contribution-row" key={name}><span>{name}</span><strong>{value}</strong></div>)}<button className="text-button">View full breakdown ↗</button></section> }
function Filters({ route, airline, window, setRoute, setAirline, setWindow }: any) { return <section className="filter-bar"><div className="filter-title"><Filter size={16} /><strong>Filter dataset</strong></div><label>Route<select value={route} onChange={e => setRoute(e.target.value)}>{routes.map(x => <option key={x}>{x}</option>)}</select></label><label>Airline<select value={airline} onChange={e => setAirline(e.target.value)}>{airlines.map(x => <option key={x}>{x}</option>)}</select></label><label>Booking window<select value={window} onChange={e => setWindow(e.target.value)}>{windows.map(x => <option key={x}>{x}</option>)}</select></label><button className="reset-button" onClick={() => { setRoute(routes[0]); setAirline(airlines[0]); setWindow(windows[0]) }}>Reset</button></section> }
function Analysis(props: any) { return <><Filters {...props} /><div className="three-col"><MetricPanel title="Route fare profile" metric="₹5,481" caption="average fare" values={['₹3,124 min','₹8,920 max','N = 220']} /><MetricPanel title="Airline fare profile" metric="₹5,912" caption="average fare" values={['₹3,645 min','₹9,118 max','N = 220']} /><MetricPanel title="Booking-window effect" metric="+18.4%" caption="0–3 vs 31–60 days" values={['0–3 days  ₹6,852','8–15 days  ₹5,204','31–60 days  ₹4,218']} /></div><section className="panel"><PanelTitle eyebrow="COMPARATIVE VIEW" title="Fare profiles by segment" /><div className="bar-list">{['DEL–BOM','BLR–CCU','BOM–HYD','DEL–BLR'].map((x, i) => <div className="bar-row" key={x}><span>{x}</span><div className="bar-track"><i style={{ width: `${88 - i * 14}%` }} /></div><strong>₹{formatNumber(6212 - i * 487)}</strong></div>)}</div></section></> }
function MetricPanel({ title, metric, caption, values }: any) { return <section className="panel metric-panel"><p className="eyebrow">{title}</p><strong className="metric-value">{metric}</strong><span>{caption}</span><div className="metric-values">{values.map((v: string) => <span key={v}>{v}</span>)}</div></section> }
function Disparity(props: any) { return <><Filters {...props} /><div className="two-col"><MetricPanel title="Network fare spread" metric="42.7%" caption="coefficient of variation" values={['Route spread 38.1%','Airline spread 24.6%','N = 660']} /><section className="panel"><PanelTitle eyebrow="DISPERSION ALERT" title="Highest observed disparity" /><div className="alert-stat"><strong>DEL–BOM</strong><span>₹3,124 — ₹9,118</span><em>+65.7% spread</em></div><div className="mini-legend"><i className="low" />Lower fare <i className="high" />Higher fare</div></section></div><section className="panel"><PanelTitle eyebrow="ROUTE × BOOKING WINDOW" title="Average fare heatmap" /><div className="heatmap"><div></div>{windows.slice(1).map(x => <span key={x}>{x.replace(' days','')}</span>)}{['DEL–BOM','BLR–CCU','BOM–HYD','DEL–BLR'].map((r, ri) => <div className="heat-row" key={r}><strong>{r}</strong>{windows.slice(1).map((_, i) => <span className={`heat h${(ri + i) % 5}`} key={i}>₹{formatNumber(6800 - (i * 460) - (ri * 210))}</span>)}</div>)}</div></section></> }
function DataQuality() { return <><div className="three-col"><MetricPanel title="Validation rules" metric="6 / 6" caption="passing checks" values={['Completeness 100%','Range checks 100%','Uniqueness 100%']} /><MetricPanel title="Flagged observations" metric="12" caption="synthetic anomaly feed" values={['2.1% of records','8 reviewed','4 pending']} /><MetricPanel title="Index safety check" metric="₹5,412" caption="cleaned average" values={['Raw average ₹5,638','Prevented impact +4.2 pts','Status protected']} /></div><section className="panel"><PanelTitle eyebrow="AUDIT LEDGER" title="Validation rule breakdown" /><div className="quality-list">{['Required fields present','Fare within route bounds','Departure date valid','Duplicate record check','Airline code recognised','Booking window consistent'].map(x => <div key={x}><FileCheck2 size={17} /><span>{x}</span><strong className="pass">PASS</strong></div>)}</div></section><section className="panel"><PanelTitle eyebrow="FLAGGED OBSERVATIONS" title="Synthetic anomaly audit" /><div className="table-scroll"><table><thead><tr><th>Record</th><th>Rule</th><th>Value</th><th>Status</th></tr></thead><tbody>{[['OBS-00491','Fare spike','₹14,882','Reviewed'],['OBS-00512','Duplicate hash','BLR–CCU / 6E','Reviewed'],['OBS-00602','Departure mismatch','2026-10-44','Pending']].map(r => <tr key={r[0]}>{r.map((x, i) => <td key={x} className={i === 3 ? 'status-cell' : ''}>{x}</td>)}</tr>)}</tbody></table></div></section></> }
function Statistics() { return <><section className="panel metadata"><PanelTitle eyebrow="DATASET METADATA" title="Measurement frame" /><div className="metadata-grid">{[['Dataset','AirFare synthetic index v1'],['Base period','2026-01-30 = 100'],['Methodology','v1_equal_route_weight'],['Route weights','All route weights 1.0'],['Observation window','30 Jan – 20 Sep 2026'],['Coverage','22 routes · 660 records']].map(([a,b]) => <div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></section><section className="panel"><PanelTitle eyebrow="METHODOLOGY" title="Five-step index construction" /><div className="method-flow">{['Collect fare observations','Validate and clean records','Aggregate by route','Apply equal route weights','Publish index and trace'].map((x,i) => <div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></section><section className="panel"><PanelTitle eyebrow="MONTHLY SERIES" title="Published fare index" /><div className="table-scroll"><table><thead><tr><th>Month</th><th>Index</th><th>Observations</th><th>Routes</th><th>Change</th></tr></thead><tbody>{[['Jan 2026','100.00','420','18','—'],['Mar 2026','112.41','516','20','+12.41%'],['Jun 2026','126.77','612','22','+12.77%'],['Sep 2026','128.18','660','22','+1.11%']].map(r => <tr key={r[0]}>{r.map((x,i)=><td key={x} className={i>0?'numeric':''}>{x}</td>)}</tr>)}</tbody></table></div></section></> }
function Benchmark() { return <><div className="two-col"><MetricPanel title="Backtest coverage" metric="100%" caption="published days reconstructed" values={['246 / 246 days','660 latest records','22 routes']} /><section className="panel benchmark-card"><PanelTitle eyebrow="RECONSTRUCTION STATUS" title="Index integrity" /><div className="integrity"><ShieldCheck size={28} /><strong>Verified</strong><span>Stored contribution records rebuild every published index within rounding tolerance.</span></div></section></div><section className="panel"><PanelTitle eyebrow="DGCA CONTEXT" title="Benchmark comparison" /><p className="body-copy">The backtest demonstrates traceability by summing stored route, airline and booking-window contribution records to reconstruct the published synthetic index. This prototype does not represent or reproduce official DGCA statistics.</p><div className="benchmark-bars">{[['Published index','128.18'],['Reconstructed','128.18'],['Difference','0.00']].map((x,i)=><div key={x[0]}><span>{x[0]}</span><div><i style={{ width: `${[91,91,3][i]}%` }} /></div><strong>{x[1]}</strong></div>)}</div></section></> }
function ApiDocs() { return <><section className="panel api-intro"><div className="api-symbol"><Database size={22} /></div><div><p className="eyebrow">READ-ONLY REST API</p><h2>Trace the published signal</h2><p className="panel-subtitle">Three JSON endpoints expose the same synthetic records used in this dashboard.</p></div></section><div className="api-list">{[['/api/v1/index','Published index series','Returns date, index, observations and route coverage.'],['/api/v1/traceability','Contribution chain','Returns route, airline, booking-window and fare contribution records.'],['/api/v1/metadata','Dataset metadata','Returns methodology, base period and coverage details.']].map(([path,title,desc])=><section className="panel api-card" key={path}><div><code>GET</code><h3>{path}</h3><p>{title} · {desc}</p></div><button className="outline-button"><Search size={15} /> Try API</button></section>)}</div><section className="panel code-panel"><PanelTitle eyebrow="EXAMPLE REQUEST" title="Fetch the index" /><pre><code>{`fetch('/api/v1/index?date=2026-09-20')\n  .then(response => response.json())\n  .then(data => console.log(data))`}</code></pre><div className="notice"><ShieldCheck size={16} /><span>Synthetic data notice: API responses are simulated and must not be used as official statistics.</span></div></section></> }
function PanelTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="panel-header"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></div> }
